### ISSUE TITLE
Re: 'Introduction'

### ISSUE THREAD

**Issue by paulrobertlloyd** [DFE-Digital/apply-for-postgraduate-teacher-training-tech-docs#53]
Problem with 'Introduction' (apply-for-postgraduate-teacher-training-tech-docs.cloudapps.digital/):

Currently, this page says:

> Your existing users will be grant your SRS access to the Apply API on their behalf via DfE Sign-in

Should this be ‘your existing user will grant your SRS access’?

**Comment by tijmenb** [comment]
Fixed in https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training-tech-docs/pull/77, thanks Paul.
